syntax = "proto3";

package webauthn.ceremony;

import "webauthn/authenticator/assertion/response.proto";
import "webauthn/authenticator/attachment.proto";
import "webauthn/credential.proto";
import "webauthn/extensions/response.proto";
import "webauthn/public_key_credential/type.proto";

message Assertion {
  webauthn.Credential credential = 1;
  public_key_credential.Type type = 2;
  authenticator.Attachment authenticator_attachment = 3;
  extensions.Response client_extension_results = 4;
  authenticator.assertion.Response response = 5;
}
