syntax = "proto3";

package webauthn.public_key_credential;

import "webauthn/ceremony/challenge.proto";
import "webauthn/extensions/request.proto";
import "webauthn/public_key_credential/descriptor.proto";
import "webauthn/public_key_credential/user_entity.proto";
import "webauthn/relying_party/conveyance_preference.proto";
import "webauthn/relying_party/entity.proto";
import "webauthn/relying_party/parameters.proto";
import "webauthn/relying_party/selection_criteria.proto";

message CreationOptions {
  ceremony.Challenge challenge = 1;
  uint32 timeout = 2;
  relying_party.Entity rp = 3;
  UserEntity user = 4;
  repeated relying_party.Parameters pub_key_cred_params = 5;
  repeated Descriptor exclude_credentials = 6;
  relying_party.SelectionCriteria authenticator_selection = 7;
  repeated string hints = 8;
  relying_party.ConveyancePreference attestation = 9;
  repeated string attestation_formats = 10;
  extensions.Request extensions = 11;
}
